spring:
  h2:
    console:
      enabled: true


      datasource:
        hikari:
          diver-class-name: org.h2.Driver
          jdbc-url: jdbc:h2:~/test
          username: sa
          password:

mybatis:
  mapper-locations:
  - mappers/*.xml

